CREATE SCHEMA MANAGEDB;

CREATE TABLE MANAGEDB.USER
(
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(64) not null,
	USERNAME VARCHAR(64) not null,
	PASSWORD VARCHAR(128) not null,
    PHONENUM varchar (64) not null,
	ROLE VARCHAR(64) not null,
    EMAIL VARCHAR(60) not null,
    DEL BOOLEAN DEFAULT 0 ,
	CONSTRAINT USERS_USERNAME_UINDEX UNIQUE (USERNAME)
);

INSERT INTO MANAGEDB.USER (ID, NAME, USERNAME, PASSWORD,PHONENUM , ROLE , EMAIL) VALUES (1, 'Administrator', 'admin', 'admin','010','admin','admin@email.com');
INSERT INTO MANAGEDB.USER (ID, NAME, USERNAME, PASSWORD,PHONENUM , ROLE , EMAIL) VALUES (2, 'Amr', 'amr_100', 'user','012', 'user' , 'amr@email.com');
INSERT INTO MANAGEDB.USER (ID, NAME, USERNAME, PASSWORD,PHONENUM , ROLE , EMAIL) VALUES (3, 'Ayman', 'ayman_100', 'guest','013' , 'user' , 'ayman@email.com');
SELECT * FROM MANAGEDB.USER;

CREATE TABLE MANAGEDB.GROUP
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    GROUPNAME varchar(60) not null,
    DESCRIPTION varchar(100) not null
);

INSERT INTO MANAGEDB.GROUP (ID,GROUPNAME,DESCRIPTION) VALUES (1,'Gym&Fitness','Group for workout enthusiasts');
INSERT INTO MANAGEDB.GROUP (ID,GROUPNAME,DESCRIPTION) VALUES (2,'web dev','Group for web dev');
CREATE TABLE  MANAGEDB.GROUP_MEMBERS (
    USERID BIGINT not null,
    GROUPID BIGINT not null,
   
    FOREIGN KEY (USERID) REFERENCES MANAGEDB.USER (ID),
    FOREIGN KEY (GROUPID) REFERENCES MANAGEDB.GROUP (ID),
     PRIMARY KEY (USERID, GROUPID)
  
);

INSERT INTO MANAGEDB.GROUP_MEMBERS (USERID, GROUPID)
VALUES (1,1);

UPDATE MANAGEDB.USER SET PASSWORD = MD5(PASSWORD)